apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "dogbreed-chart.fullname" . }}
  labels:
    {{- include "dogbreed-chart.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: dogbreed.jimoh.xyz
      http:
        paths:
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: release-name-dogbreed-chart-backend
                port:
                  number: 80
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: release-name-dogbreed-chart-frontend
                port:
                  number: 80
              
             