apiVersion: v1
kind: Service
metadata:
  name: {{ include "dogbreed-chart.fullname" . }}-frontend
  labels:
    {{- include "dogbreed-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceFe.type }}
  ports:
    - port: {{ .Values.serviceFe.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: release-name-dogbreed-chart-frontend
