

pipeline{
    agent any
    tools {nodejs "Node"}

    stages {
        stage("Checkout target branch") {
            steps {
                checkout scm
            }
        }
        stage ("build and publish") {
            steps {
                dir 'frontend/'
                sh 'docker build -t dogbreed-fe-get:process-auto1 .'
            }
        }
    }
}
