

pipeline{
    agent any
    // tools {nodejs "Node"}

    stages {
        /* groovylint-disable-next-line UnnecessaryGString */
        stage("Checkout target branch") {
            steps {
                checkout scm
            }
        }
        /* groovylint-disable-next-line UnnecessaryGString */
        stage ("build and publish") {
            steps {
                sh 'cd frontend && docker build -t dogbreed-fe-get .'
            }
        }
    }
}
